### ISSUE TITLE
http://localhost?type=json type not working

### ISSUE THREAD

**Issue by samtheprogrammer** [omphalos/crud-file-server#6]
I am trying to access a folder passing type = json i am still getting html page back 
<html>
    <body>
        <p>
            <a href="/App1">App1</a>
        </p>
        <p>
            <a href="/App2">App2</a>
        </p>
        <p>
            <a href="/App3">App3</a>
        </p>
    </body>
</html>

**Comment by omphalos** [comment]
Thanks for the bug report.  Fixed in 0.7.0.  If you run into another problem please let me know!
