### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [omphalos/crud-file-server#7]
Hi,

I'm a member of the Node.js Security WG and we received a report regarding a security issue with this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by omphalos** [comment]
@lirantal fixed and published, thanks for the report.  Sorry I don't check that email too often.

**Comment by omphalos** [comment]
@bl4de thank you for your help!

**Comment by bl4de** [comment]
@omphalos  You're welcome :)

**Comment by bl4de** [comment]
@omphalos Just checked right now - you have fixed an issue with sanitizing file names rendered in html.

Are you aware about another issue reported to Hacker One? Probably @lirantal contacted you because of that report, not the one you have resolved :)

**Comment by lirantal** [comment]
@omphalos thanks for fixing the issue indeed, but there's a couple of items we need your assistance with. Can you please join the conversation on the Hacker1 platform to collaborate with the bug hunter about this report? You should've received an invite in your inbox

**Comment by omphalos** [comment]
@lirantal, I joined - we can continue the discussion there.

**Comment by lirantal** [comment]
Thanks indeed! :-)
